jobs:
  post-comment:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: haya14busa/action-workflow_run-status@v1
    - continue-on-error: true
      name: Download artifact
      uses: actions/github-script@v6
      with:
        script: "let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \   owner: context.repo.owner,\n   repo: context.repo.repo,\n   run_id:\
          \ context.payload.workflow_run.id,\n});\nlet matchArtifact = allArtifacts.data.artifacts.filter((artifact)\
          \ => {\n  return artifact.name == \"env\"\n})[0];\nlet download = await\
          \ github.rest.actions.downloadArtifact({\n   owner: context.repo.owner,\n\
          \   repo: context.repo.repo,\n   artifact_id: matchArtifact.id,\n   archive_format:\
          \ 'zip',\n});\nlet fs = require('fs');\nfs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/env.zip`,\
          \ Buffer.from(download.data));\n"
    - continue-on-error: true
      name: Unzip artifact
      run: "unzip env.zip\nls -ltR\nwhile read line; do\n  echo \"$line\" >> $GITHUB_ENV\n\
        done < env\n"
    - continue-on-error: true
      if: github.event.workflow_run.event == 'pull_request'
      name: Post PR comment
      uses: mshick/add-pr-comment@v2
      with:
        issue: ${{ env.PR_NUMBER }}
        message: '**Snapshot Tests**

          **API 23**: [Report](https://happo.io/a/27/report/${{ env.GITHUB_SHA }}-android23)
          [Diff](https://happo.io/a/27/p/27/compare/master-android23/${{ env.GITHUB_SHA
          }}-android23)

          **API 31**: [Report](https://happo.io/a/27/report/${{ env.GITHUB_SHA }}-android31)
          [Diff](https://happo.io/a/27/p/27/compare/master-android31/${{ env.GITHUB_SHA
          }}-android31)'
        message-id: ${{ env.GITHUB_SHA }}
name: Post PR comment
on:
  repository_dispatch:
    types: trigger-ga___post_snapshot_comment.yml
