jobs:
  api-compatibility:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Run API compatibility check
      run: ./gradlew apiCheck --no-daemon
  deploy:
    if: github.event_name == 'push' && github.repository == 'airbnb/lottie-android'
      && github.ref == 'refs/heads/master'
    needs:
    - lint
    - unit-test
    - gradle-wrapper
    - snapshot-tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: Deploy Snapshot
      run: ./deploy_snapshot.sh
  gradle-wrapper:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Run Lint
      run: ./gradlew lintDebug --no-daemon
    - continue-on-error: true
      if: always()
      name: Zip reports
      run: zip -r reports.zip . -i '**/reports/*.xml' '**/reports/*.html'
    - continue-on-error: true
      if: always()
      name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: lint_reports
        path: reports.zip
  snapshot-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup env
      run: "curl https://us-central1-lottie-snapshots.cloudfunctions.net/snapshot-env-v1/emulator\
        \ > snapshot-env\nwhile read line; do\n  echo \"$line\" >> $GITHUB_ENV\ndone\
        \ < snapshot-env\n"
      shell: bash
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build app
      run: ./gradlew snapshot-tests:assembleDebug snapshot-tests:assembleDebugAndroidTest
        --no-daemon
    - continue-on-error: true
      name: Run tests
      uses: emulator-wtf/run-tests@v0.9.6
      with:
        api-token: ${{ env.EW_API_TOKEN }}
        app: snapshot-tests/build/outputs/apk/debug/snapshot-tests-debug.apk
        devices: 'model=Pixel2,version=23,gpu=auto

          model=Pixel2,version=31,gpu=auto

          '
        outputs-dir: build/test-results
        test: snapshot-tests/build/outputs/apk/androidTest/debug/snapshot-tests-debug-androidTest.apk
        version: 0.9.19
    - continue-on-error: true
      env:
        PR_NUMBER: ${{ github.event.number }}
      if: github.event_name == 'pull_request'
      name: Save PR number
      run: 'mkdir -p ./env

        echo PR_NUMBER=$PR_NUMBER > ./env/env

        echo GITHUB_SHA=${{ github.sha }} >> ./env/env

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: env
        path: env/
  unit-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --no-daemon
    - continue-on-error: true
      if: always()
      name: Zip reports
      run: zip -r reports.zip . -i '**/reports/*.xml' '**/reports/*.html'
    - continue-on-error: true
      if: always()
      name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_reports
        path: reports.zip
name: Validate
on:
  repository_dispatch:
    types: trigger-ga___validate.yml
